import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    //absolute:"",
    default:"NEXT JS DEMO",
      template:"%s | Next js"
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "royalblue", padding: "1rem" }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: "ghostwhite", padding: "1rem" }}>
          <p>Footer </p>
        </footer>
      </body>
    </html>
  );
}
